### ISSUE TITLE
Some findings about the short-term memory

### ISSUE THREAD

**Issue by L-M-Sherlock** [open-spaced-repetition/short-term-memory-research#1]
@Expertium, I found that the same-day reviews have a significant impact.

![image](https://github.com/open-spaced-repetition/short-term-memory-research/assets/32575846/b342b197-903e-4603-9b48-bd5ce2051347)

![image](https://github.com/open-spaced-repetition/short-term-memory-research/assets/32575846/3f199ca6-f058-4656-9391-5be4d78ce257)

![image](https://github.com/open-spaced-repetition/short-term-memory-research/assets/32575846/6fd73b3d-8223-4968-85c5-9545fea22c87)

![image](https://github.com/open-spaced-repetition/short-term-memory-research/assets/32575846/eee003d7-b3f5-446b-a03d-92ef91876f7e)

![image](https://github.com/open-spaced-repetition/short-term-memory-research/assets/32575846/67d31c72-78df-4ea1-b767-5b1b9ac54cf9)

![image](https://github.com/open-spaced-repetition/short-term-memory-research/assets/32575846/12ef5587-267f-401f-ac12-9de7dc074927)

![image](https://github.com/open-spaced-repetition/short-term-memory-research/assets/32575846/36c69093-1d8a-471d-b389-09e1d4c2ed7e)

**Comment by Expertium** [comment]
Interesting. Do you have any ideas how to use these findings to improve FSRS? Perhaps we can add same-day reviews to the estimation of S0?

Also, how is the benchmarking going?

**Comment by L-M-Sherlock** [comment]
> Interesting. Do you have any ideas how to use these findings to improve FSRS?

I attempt to include the short-term reviews with float-delta-t in FSRS. But it increased w[9] (stabilization decay) drastically. In other word, the `factor` is very large in the early steps.The short-term memory seems to has very different stabilization process in contrast with the long-term memory.

> Also, how is the benchmarking going?

It stuck. It will take 100+ hours to run the benchmark (and my computer cannot do anything else during the period). Converting FSRS from a seq-to-one model to a seq-to-seq model could speed it up. But it's not compatible with TimeSeriesSplit.

**Comment by Expertium** [comment]
Try to include same-day reviews in the estimation of S0.
As for benchmarking, maybe it's really time to rewrite everything in Rust? Well, either that, or run the benchmark but reduce `num_threads`. That's what I did to be able to use my computer while the benchmark is running. It will be slower, of course, but 100-200 hours isn't as bad as I was expecting. I could do that for you, if you make the dataset downloadable.

**Comment by L-M-Sherlock** [comment]
OK. I'm developing a new pre-process script for the benchmark, because I need to save my disk size :). `t_history` and `r_history` will not stored in the dataset files.

**Comment by Expertium** [comment]
> `t_history` and `r_history` will not stored in the dataset files.

Then how will the optimizer work without them? How will they be stored?

**Comment by L-M-Sherlock** [comment]
> Then how will the optimizer work without them?

I find an efficient way to build these features from the raw data.

**Comment by Vilhelm-Ian** [comment]
what do the blue bubbles represent

**Comment by L-M-Sherlock** [comment]
https://github.com/open-spaced-repetition/short-term-memory-research/blob/6913c5685ab8a6ebb6ccc55ef67df5856e89e2df/script.py#L64

**Comment by Expertium** [comment]
I have an idea: maybe we could do the same thing we do for S0, but for learning steps?
1) Use only same-day reviews
2) Calculate the average stability for those, using the curve-fitting method that we use for S0
3) Output that value of S0_short_term and tell the user to use it as a learning step

This could be called "Compute optimal learning steps", a new feature.

**Comment by Expertium** [comment]
Using your graph as an example, here the learning step would be 7m
![image](https://github.com/open-spaced-repetition/short-term-memory-research/assets/83031600/eb781891-584a-4e8c-8223-e707ce87b003)

**Comment by Vilhelm-Ian** [comment]
> This could be called "Compute optimal learning steps", a new feature.

I was hoping something like this came to be

**Comment by Vilhelm-Ian** [comment]
@L-M-Sherlock were this finding used in the 4.5 release. What were the changes for 4.5 and are there benchmark results

**Comment by L-M-Sherlock** [comment]
It wasn't. I still didn't find out a clear pattern of short-term memory.
